### ISSUE TITLE
怎么使用path-to-regexp插件

### ISSUE THREAD

**Issue by Totoro1998** [yunsii/vite-react#1]
使用path-to-regexp插件时，会报错

 > node_modules/react-router/esm/react-router.js:9:7: error: No matching export in "node_modules/path-to-regexp/dist.es2015/index.js" for import "default"
    9 │ import pathToRegexp from 'path-to-regexp';
      ╵        ~~~~~~~~~~~~

error when starting dev server:
Error: Build failed with 1 error:
node_modules/react-router/esm/react-router.js:9:7: error: No matching export in "node_modules/path-to-regexp/dist.es2015/index.js" for import "default"

**Comment by yunsii** [comment]
确实会报错，研究了一下，应该是 esbuild 导致的，可以看看 react-router 对于 pathToRegexp 的用法 https://github.com/ReactTraining/react-router/search?q=import+pathToRegexp+from+%27path-to-regexp%27 又 pathToRegexp 是没有默认导出的，应该是这个原因导致了。尝试升级 vite 到最新版，好像又没这个问题了，你可以试试。

**Comment by Totoro1998** [comment]
"vite": "^2.1.2",
    "vite-plugin-compression": "^0.2.3",
    "vite-plugin-style-import": "^0.8.1",
    "vite-plugin-svg-icons": "^0.4.0"
还是有这种问题

**Comment by yunsii** [comment]
我是在 gitpod 测试的，你可以看看 https://tan-prawn-tpfzf3n6.ws-eu03.gitpod.io/#/workspace/vite-react

**Comment by yunsii** [comment]
Closing as stale
