### ISSUE TITLE
How to add <ConfigProvider>?

### ISSUE THREAD

**Issue by d9k** [yunsii/vite-react#6]
Hello! How can I add config provider to your template like ant.design tutorial says?
https://ant.design/docs/react/i18n#ConfigProvider

Where can I find root html template?

**Comment by yunsii** [comment]
Here: [/src/layouts/BlankLayout.tsx](https://github.com/yunsii/vite-react/blob/master/src/layouts/BlankLayout.tsx)，it is render component of [root route](https://github.com/yunsii/vite-react/blob/master/config/routes.ts#L4). Like below:

```ts
const Layout: React.FC = ({ children }) => {
  return <ConfigProvider>{children}</ConfigProvider>;
};

export default Layout;
```

**Comment by d9k** [comment]
@yunsii, thanks, it worked. 

I suggest to rename BlankLayout to RootLayout. Also exported member: Layout to RootLayout for ease of debugging.

**Comment by yunsii** [comment]
@d9k PR is welcome 👀

**Comment by yunsii** [comment]
> I suggest to rename BlankLayout to RootLayout. Also exported member: Layout to RootLayout for ease of debugging.

Done.
